import './manifest';
import '#@/lib/styles/globals.css';
import 'material-symbols';
import { ReactNode, Suspense } from 'react';
import { Metadata, Viewport } from 'next';
import { josefina, playDisp, ptserif, radio, raleway } from '#@/lib/styles/fonts';
import { Loader } from '#@/lib/components/Loader/main-loader';
import PushManagerComponent from '#@/lib/components/PushManager';
import { ModalProvider } from './context/modal-context';
import { NavigationContextProvider } from './context/navigation-context';
import { PushNotificationProvider } from './context/pushNotificationContext';
import { SearchProvider } from './context/search-context';
import layout from '#@/lib/styles/layout.module.css';
import { NavBar } from '#@/lib/components/layout/NavBar';

const prefix = process.env.NODE_ENV === 'production'
  ? 'app'
  : 'beta';

const hostname = `https://${ prefix }.rsasesorjuridico.com`;

export const metadata: Metadata = {
  metadataBase   : new URL( hostname ),
  title          : 'R&S Asesoría Jurídica',
  description    : 'Generated by create next app',
  generator      : 'R&S Asesoría Jurídica',
  applicationName: 'R&S Asesoría Jurídica',
  referrer       : 'origin-when-cross-origin',
  keywords       : [
    'Next.js',
    'React',
    'JavaScript'
  ],
  authors: [
    {
      name: 'Camilo Suarez',
    },
    {
      name: 'Cachorro Cami',
      url : hostname,
    },
  ],

  creator        : 'Cachorro Cami',
  publisher      : 'CachorroC',
  alternates     : {},
  formatDetection: {
    email    : false,
    address  : false,
    telephone: false,
  },
  appleWebApp: {
    capable       : true,
    title         : 'R y S',
    statusBarStyle: 'black-translucent',
    startupImage  : [
      'src/app/logo.svg',
      {
        url  : '/logo.svg',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url            : '/',
      should_fallback: true,
    },
  },
};

export const viewport: Viewport = {
  width            : 'device-width',
  initialScale     : 1,
  maximumScale     : 1,
  colorScheme      : 'light dark',
  interactiveWidget: 'resizes-content',
  themeColor       : [
    {
      media: '(prefers-color-scheme: light)',
      color: '#5C6BC0',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#1A237E',
    },
  ],
};

export default function RootLayout( {
  children,
  modal,
}: {
  children: ReactNode;
  modal   : ReactNode;
} ) {
  return (
    <html lang="es-CO">
      <body
        className={`${ playDisp.variable } ${ josefina.className } ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]`}
      >
        <PushNotificationProvider>

          <NavigationContextProvider>
            <SearchProvider>
              <ModalProvider>

                <PushManagerComponent />
                <div className={layout.container}>
                  <Suspense
                    fallback={
                      <nav>
                        Cargando menú... <Loader />
                      </nav>
                    }
                  >
                    <NavBar />
                  </Suspense>
                  {children}
                  {modal}
                </div>

              </ModalProvider>
            </SearchProvider>
          </NavigationContextProvider>

        </PushNotificationProvider>
        {/*  <Script
          src={`https://${ prefix }.rsasesorjuridico.com/install-service-worker.js`}
        /> */}
      </body>
    </html>
  );
}
